swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
  - text/html
paths:
  /wish:
    x-swagger-router-controller: wish
    get:
      description: 'Get all wishes'
      operationId: getWishes
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Wish"
    post:
      description: Add wish
      operationId: addWish
      parameters:
        - name: wish
          in: body
          description: 'Wish data'
          required: true
          schema:
            $ref: "#/definitions/Wish"
      responses:
        "200":
          description: Success
          schema:
            type: string
        "501":
          description: Internal server error
          schema:
            type: string
  /wish/{wishId}:
    x-swagger-router-controller: wish
    get:
      description: 'Get wish by id'
      operationId: getWishById
      parameters:
        - name: wishId
          in: path
          description: 'Wish id'
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Wish"
  /thumbnail/generate:
      x-swagger-router-controller: thumbnail
      get:
        description: Generates web-site thumbnail
        operationId: generate
        parameters:
          - name: url
            in: query
            description: Web site where thumbnail is looked up
            required: true
            type: string
        produces:
          - image/png
          - image/svg+xml
          - image/jpeg
        responses:
          "200":
            description: Success
            schema:
             type: file
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Wish:
    properties:
      description:
        type: string
